In [1]:
%load_ext autoreload
%autoreload 2

In [7]:
folder_of_data = "/home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep"

In [8]:
!pip3 install matplotlib
!pip3 install pandas
!pip3 install h5py
!pip3 install scipy numba cython multiprocess boost==1.74

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /home/ceas/enserrog/.local/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: contourpy>=1.0.1 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from matplotlib) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.23 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /shared/python/python39/lib/python3.9/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /shared/python/python39/lib/python3.9/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in /shared/python/python39/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.21.0)
Requirement already satisfied: six>=1.5 in /shared/python/python39/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/ceas/enserrog/.local/lib/python3.9/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.22.4 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /shared/python/python39/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /shared/python/python39/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: h5py in /home/ceas/enserrog/.local/lib/python3.9/site-packages (3.14.0)
Requirement already satisfied: numpy>=1.19.3 in /home/ceas/enserrog/.local/lib/python3.9/site-packages (from h5py) (2.0.2)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scipy in /home/ceas/enserrog/.local/lib/python3.9/site-packages (1.13.1)
Requirement already satisfied: numba in /home/ceas/enserrog/.local/lib/python3.9/site-packages (0.60.0)
Requirement already satisfied: cython in /home/ceas/enserrog/.local/lib/python3.9/site-packages (3.2.4)
Requirement already satisfied: multiprocess in /home/ceas/enserrog/.local/lib/python3.9/site-packages (0.70.19)
ERROR: Could not find a version that satisfies the requirement boost==1.74 (from versions: 0.1)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
ERROR: No matching distribution found for boost==1.74

In [9]:
import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

In [10]:
from src.util import find_file_recursive
from src.processing import process_session

In [34]:
# review files of path saved in folder_of_data variables
# not all mice have full data, still working on incomplete mice
# This will help you select which csv in the path to use
folder_of_data = "/home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep"

all_reach_states = find_file_recursive(folder_of_data, "results.csv")

session_ = {}

for rep in all_reach_states:
    rep_id = rep.split("/")[-2]
    session_[rep_id] = pd.read_csv(rep)

pd.concat(session_.values())

📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep
  ❌ 'results.csv' not found
  📂 Found 10 subdirectories
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/1
    ✅ Found 'results.csv'
    📂 Found 4 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/1/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/1/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/1/ties
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/1/.ipynb_checkpoints
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/2
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/2/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/2/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/2/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/3
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/3/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/3/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/3/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/4
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/4/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/4/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/4/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/5
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/5/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/5/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/5/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/6
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/6/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/6/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/6/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/7
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/7/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/7/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/7/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/8
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/8/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/8/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/8/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/9
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/9/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/9/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/9/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/10
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/10/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/10/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep/10/ties
      ❌ 'results.csv' not found

,Unnamed: 0,energy_wins,firing_wins,ties,n_sessions,energy_win_pct,mean_energy_distance,mean_firing_distance,std_energy_distance,std_firing_distance,mean_covariance,mean_correlation,energy_min_wins,energy_max_wins,firing_min_wins,firing_max_wins,stim,rep
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,0
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,0
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,0
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,2
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,2
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,2
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,3
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,3
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,3
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,4
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,4
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,4
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,5
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,5
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,5
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,6
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,6
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,6
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,7
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,7
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,7
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,8
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,8
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,8
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,9
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,9
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,9
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,10
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,10
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,10

In [35]:
folder_of_data = "/home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms"

all_reach_states = find_file_recursive(folder_of_data, "results.csv")

session_ = {}

for rep in all_reach_states:
    rep_id = rep.split("/")[-2]
    session_[rep_id] = pd.read_csv(rep)

pd.concat(session_.values())

📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms
  ❌ 'results.csv' not found
  📂 Found 10 subdirectories
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/4
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/4/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/4/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/4/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/1
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/1/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/1/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/1/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/2
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/2/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/2/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/2/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/3
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/3/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/3/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/3/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/5
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/5/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/5/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/5/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/6
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/6/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/6/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/6/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/7
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/7/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/7/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/7/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/8
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/8/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/8/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/8/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/9
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/9/energy_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/9/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/9/ties
      ❌ 'results.csv' not found
  📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/10
    ✅ Found 'results.csv'
    📂 Found 3 subdirectories
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/10/energy_wins
      ❌ 'results.csv' not found
      📂 Found 1 subdirectories
      📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/10/energy_wins/.ipynb_checkpoints
        ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/10/firing_wins
      ❌ 'results.csv' not found
    📁 Searching in: /home/ceas/enserrog/ising_EnergyOverTime/Arbitration/within_session_test_rep_10ms/10/ties
      ❌ 'results.csv' not found

,Unnamed: 0,energy_wins,firing_wins,ties,n_sessions,energy_win_pct,mean_energy_distance,mean_firing_distance,std_energy_distance,std_firing_distance,mean_covariance,mean_correlation,energy_min_wins,energy_max_wins,firing_min_wins,firing_max_wins,stim,rep
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,4
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,4
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,4
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,1
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,1
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,1
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,2
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,2
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,2
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,3
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,3
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,3
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,5
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,5
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,5
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,6
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,6
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,6
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,7
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,7
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,7
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,8
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,8
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,8
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,9
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,9
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,9
0,0,12,8,1,21,57.142857,8.619048,9.761905,5.524630,7.373729,-0.038980,-0.694953,8,4,5,3,0,10
1,1,10,11,0,21,47.619048,8.761905,8.761905,4.617820,5.723009,-0.057248,-0.720435,6,4,5,6,1,10
2,2,9,9,3,21,42.857143,7.714286,8.857143,4.871128,5.751072,-0.040277,-0.624832,6,3,6,3,2,10